### ISSUE TITLE
Create a `launch.ps1` to deploy `control`

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#100]
- Prompt for `Virtualbox` or `vCenter`
- Launch control to Virtualbox 
  - [x] Install `Chocolately` [docs](https://chocolatey.org/install)
  - [x] Install `Virtualbox` [docs](https://mohitgoyal.co/2016/12/17/install-oracle-virtual-box-using-powershell/)
  - [ ] Use `VBoxManage` to provision `control`
  - [ ] Execute `--post-install-command="start sshd"` 
- Launch control to vSphere
  - [ ] Install `PowerCLI` [docs](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.esxi.install.doc/GUID-F02D0C2D-B226-4908-9E5C-2E783D41FE2D.html)
 - [ ] As `launch.ps1` prompts the user for information about the staging network, store the information in the `config.json` that will be pushed into `Control` on creation
- [ ] Ensure a network with DHCP, access to Control, and access to the Internet exists
  - [ ] Virtualbox: Probably `bridged-adapter` 
  - [ ] vSphere: Currently `SPNT_DEV_LAN`
- [ ] Break Packer configurations into multiple build files for different providers
- [ ] In the provider specific providers, add different staging adapters

**Comment by uwardlaw** [comment]
When selection for a `provider` (vSphere or Virtualbox) is complete, `launch.ps1` also needs to ensure a network with DHCP exists for staging, per #111. Devices on the staging networking need should be able to route to the Internet and Control. The information for what network to use needs to be make it's way to the Packer templates somehow. For `vyos-core-router` these values would need to change:

```
  network_adapters {
    network      = "SPNT_DEV_LAN"
    network_card = "vmxnet3"
  }

  network_adapters {
    network      = "SPNT_DEV_LAN"
    network_card = "vmxnet3"
  }

  network_adapters {
    network      = "SPNT_DEV_LAN"
    network_card = "vmxnet3"
  }
```

**Comment by uwardlaw** [comment]
Merged #15, which is a subset of this issue

**Comment by rylagek** [comment]
When testing `vboxmanage` commands, I broke VirtualBox. Error was `Failed to acquire VirtualBox COM object` 
Uninstall/Reinstall did not work.
Turns out I had corrupted something inside .VirtualBox (likely VirtualBox.xml)
**Solution: remove the .VirtualBox folder so it is recreated by VirtualBox**

**Comment by marissaeinhorn** [comment]
Replaces day 0 deployment instructions for students at home and for enterprise deployments

**Comment by rylagek** [comment]
[This](https://nsis.sourceforge.io/Main_Page) scriptable windows installer could definitely be used to help package up launch in the future. It's what `nmap` uses for their self-installer

**Comment by marissaeinhorn** [comment]
Control will not be supporting as many core services once we transition to the RANS.  Closing this issue and will describe remaining setup requirements in #230
