### ISSUE TITLE
Automatically build the CLI from `[service].py` files

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#101]
To improve the extensibility of the CLI, we should implement an `automatic` CLI that builds different options out of `argparse` from the functions defined in a `[service].py`. This way in the future, we should only need to add new services, like `guacamole.py` and the CLI will build itself at runtime.

Here's some code to ~~steal~~...~~inspect~~ draw inspiration from. 

https://codereview.stackexchange.com/questions/190774/autogenerate-a-cli-for-python-functions

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or intermediate solution
