### ISSUE TITLE
Overwrite the configuration file options with command line arguments

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#104]

**Comment by marissaeinhorn** [comment]
@uwardlaw what is the use case for overwriting the configuration file?

**Comment by uwardlaw** [comment]
This was refereing to overriding items in `config.json` from command line. This would allow temporary adjustments to using the `CLI` particularly for testing or scripting alternate use cases.

I imagined something like `vater restart -c host.project_path="/home/test_control"`.

Where `host.project_path` is from the `config.json`:

```json
{ 
  "dev" : { "enable" : true },
  "host" : { 
      "hostname" : "control",
      "project_path" : "/home/control/"
    },
```

And then an entirely new project could be referenced and used.

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or intermediate solution
