### ISSUE TITLE
`put` after recheck for changed token in `semaphore.py` fails

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#107]
```
{'_content': b'{"error":"Environment ID in body and URL must be the same"}\n',
 '_content_consumed': True,
 '_next': None,
 'connection': <requests.adapters.HTTPAdapter object at 0x7f5450342e20>,
 'cookies': <RequestsCookieJar[]>,
 'elapsed': datetime.timedelta(microseconds=4051),
 'encoding': None,
 'headers': {'Content-Type': 'application/json', 'Date': 'Tue, 30 Nov 2021 20:37:26 GMT', 'Content-Length': '60'},
 'history': [],
 'raw': <urllib3.response.HTTPResponse object at 0x7f54502ed760>,
 'reason': 'Bad Request',
 'request': <PreparedRequest [PUT]>,
 'status_code': 400,
 'url': 'http://192.168.100.1:4000/api/project/1/environment/1'}
Response 400, Bad request
```

`semaphore.py`
```
237         if self.wasTokenGenerated:
238             self.api.put(
239                 url=self.cfg['semaphore']['api']['project_environment'] + (
240                         '/' + str(self.envId)
241                     ),
242                 data = (
243                     '{'
244                     '"name": "' + name + '", '
245                     '"project_id": ' + str(self.managementProjectId) + ', '
246                     '"environment_id": ' + str(self.envId) + ', '
247                     '"json": ' + self.env + ''
248                     '}'
249                 )
250             )
```

This fixes a niche case where the token changed, but the environment was already created. This is pretty rare.

The errors comes from [source](https://github.com/ansible-semaphore/semaphore/blob/54773d0c35b611df2e41a7a1a3160edda2420433/api/projects/environment.go):
```
func UpdateEnvironment(w http.ResponseWriter, r *http.Request) {
	oldEnv := context.Get(r, "environment").(db.Environment)
	var env db.Environment
	if !helpers.Bind(w, r, &env) {
		return
	}

	if env.ID != oldEnv.ID {
				helpers.WriteJSON(w, http.StatusBadRequest, map[string]string{
					"error": "Environment ID in body and URL must be the same",
				})
		return
	}
```

For now I will comment out the code. Possible options:
- Delete and recreate the env to solve the niche case
- Write issue from semaphore-ansible with bug report

**Comment by uwardlaw** [comment]
Breaking bug, moving to requirement

**Comment by marissaeinhorn** [comment]
@uwardlaw can you add some additional context to the issue?

**Comment by uwardlaw** [comment]
@marissaeinhorn Can you ask a more specific question? I implemented a solution to fix the issue, but it didn't always work, so I removed it.

**Comment by marissaeinhorn** [comment]
There's an API key for `semaphore` its used in `self.api`.  The key is put into the environment variables within `semaphore`, this is part of the `semaphore.py` script.  Creating new projects, running tasks ect. will use this key.  

If the API key changes for any reason then the project breaks.  Solution is to remove environment & recreate a new token.  Would need to remove existing tasks and remake them.  Will probably loose the logs.  

This may no longer be an issue because tokens are never deactivated during development or in normal use.
