### ISSUE TITLE
Add debug option to the CLI

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#113]
There are various outputs that `Vater.py` and the different modules have that we don't currently print to the screen. Typically we leave `stderr` alone, but capture `stdout` and never handle it. We should introduce a verbose mode where the use can see each step happening in the code to help troubleshoot issues or have better awareness of where code execution is for longer operations.

- [ ] Add debug option to `parser.py` as a global parameter processed in the constructor (i.e. `__init__`)
- [ ] Set debug flag, `debug == true` or `debug == false` in the `config.py` so all objects that have a `configuration` object can reference it
- [ ] Go through all of the code and get verbose messages from the different tools that support it
- [ ] Print out the verbose messaging when `debug == true`

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or intermediate solution
