### ISSUE TITLE
Develop checks for all Control services and enforce dependencies

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#116]
As described in #12 and #14 (and possibly #55), attempting to configure or communicate with a service before it's completed setup causes errors.  If implementing the solution referenced in this [answer](https://stackoverflow.com/questions/25503412/how-do-i-know-when-my-docker-mysql-container-is-up-and-mysql-is-ready-for-taking#29793382):

```
while ! mysqladmin ping -h"$DB_HOST" --silent; do
    sleep 1
done
```
We will need to edit `setup.sh`.

Potentially as a [health-check](https://docs.docker.com/engine/reference/builder/#healthcheck) in the `docker-compose.yml` [file](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck), if we can make the health-check something that's blocking (meaning program execution cannot continue until the health-check returns positive), we can just insert it somewhere in `vater restart -s [service]`. Here's a decent [guide](https://scoutapm.com/blog/how-to-use-docker-healthcheck) on implementation.

- [ ] Ensure no configuration of `gitea` happens before:
  - [ ]  `gitea_db` is initialized
  - [ ]  `gitea` is ready for API calls
- [ ] Ensure no configuration of `semaphore` happens before:
  - [ ]  `semaphore_db` is initialized
  - [ ]  `semaphore` is ready for API calls
- [ ] If adding additional tools to `Control`, install them with `setup.sh`
- [ ] Test
  - [ ] With a fresh install on `Control` configured with `setup.sh`
  - [ ] With a default credential `vater restart -s gitea`, so that there is no human introduced wait time while typing in credentials, the program should wait for all dependencies to resolve before attemptng configuration
  - [ ] With a default credential `vater restart -s semaphore` (see above)

Merging #12 and #14, reopen if this implemented and the errors still persist. This is requirement because it greatly impact the development experience.

**Comment by samanthapark413** [comment]
If the health-check option is not viable, we can add checks for dependencies in `gitea.py` and `semaphore.py`

**Comment by uwardlaw** [comment]
What do you mean by checks for dependencies?

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or intermediate solution
