### ISSUE TITLE
Generic Packer Template for Rocky Linux

### ISSUE THREAD

**Issue by rylagek** [dev4vater/vater#117]
Creating Packer Template for `Rocky Linux 8.4`
- [x] get `virtualbox-iso.virtualbox` to build
- [ ] add chained builder for `vshpere`
- [ ] prep for specific template changes according to uwardlaw/vater#99

**Comment by rylagek** [comment]
Building locally on `windows 10` with `packer 1.7.8` and `virtualbox 6.1.3`

Currently hanging waiting for SSH:
`Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain`

**Comment by rylagek** [comment]
Suspect the issue with the local build might be resource related as my local `vbox` was freezing. Working on #130 with this issue to build on vSphere

**Comment by rylagek** [comment]
Working `virtualbox-iso` is in [pack_everything](https://github.com/rylagek/pack_everything)
Chaining `vsphere-iso` - currently stuck `waiting for ip`
Need to verify `VMWare Tools` presence in build - could be a known issue

**Comment by rylagek** [comment]
vSphere client showed the VM did not have an IP or DNS
Timed out waiting for IP after 30 min

**Comment by rylagek** [comment]
[Open VM Tools](https://docs.vmware.com/en/VMware-Tools/11.3.0/com.vmware.vsphere.vmwaretools.doc/GUID-C48E1F14-240D-4DD1-8D4C-25B6EBE4BB0F.html) supports `CentOS`

**Comment by rylagek** [comment]
List of [GuestOsDescriptor](https://developer.vmware.com/apis/358/vsphere/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html)

**Comment by marissaeinhorn** [comment]
Using centos instead
