### ISSUE TITLE
Implement `hub` package in `control` configured for development

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#147]
There's a tool for opening pull requests via the CLI, but requires the `hub` package. It requires configuration, and when used, prompts for username / password. This means the SSH keys needs to be altered.

```
control@control:~/vater/control-services/cli$ hub pull-request -e
github.com username: ^C
```

- [ ] Install `hub`
- [ ] Edit `setup.sh` logic for configuring keys that work with `hub` via the `~/.ssh/config`

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or interim solution
