### ISSUE TITLE
Control setup.sh failed the first time

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#149]
Followed control setup procedures poorly, ran `setup.sh` as a user other than control and changed hostname of the computer from `control` to `control-einhorn`. Reran `setup.sh` as `control` and `vater restart` command was not found. Rebooted the device twice and reran `setup.sh` to resolve the issue

**Comment by uwardlaw** [comment]
Likely related to an issue with the `bash_aliases` being sourced properly.
