### ISSUE TITLE
Create `jenkins.py` login

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#152]
Is there really a need to make logins required by services? The logins are generally stored in the `config.json` where users can set the passwords they need. If control is protected the `config.json` should be okay....

Jenkins is the first service that seamlessly took a user from configuration.

**Comment by marissaeinhorn** [comment]
Jenkins username and password is in `config.json` what else would `jenkins.py` need to accomplish?

**Comment by uwardlaw** [comment]
The functions already defined in `jenkins.py` are still needed, mostly related to the jenkins containers. You can read through the file to see some of the implemented / skeleton functions.

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or interim solution.  Detailed request for an automated testing method for Foundry content development in #236
