### ISSUE TITLE
Bug building ISOs from Semaphore

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#161]
- [x] Add path to `control` `rous/isos` in `config.py`
- [x] Add path `control` `rous/isos` to the `Management` project `env` in `semaphore.py`
- [x] Reference `env` in `group_vars/all/isos.yml`

**Comment by uwardlaw** [comment]
This whole pipe is pretty broken.

Not only was the path to build script incorrect, it wasn't pointed at `control` and the path is hardcoded. This will need a more significant rework.

**Comment by uwardlaw** [comment]
Build hung for about an hour when started from `Semaphore`:

```
11:59:33 AM TASK [Build ISOs] **************************************************************
1:04:56 PM Running playbook failed: signal: killed
```

But it built in about 15 minutes when ran locally with a:

`cd ~/rous/isos/vyos/` and `./buildVyos.sh `

**Comment by marissaeinhorn** [comment]
Potential dev task for a foundry implementation but will not be performed in semaphore.  Not required for intermediate solution.  Relevant follow on issue #234
