### ISSUE TITLE
Evaluate `control` installation on `debian 11`

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#166]
Installation of `Debian 11` from [iso](https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.2.0-amd64-netinst.iso) and compatibility testing. 40 GB disk, 1GB RAM, and 1 vcpu. 

Install time seems considerably faster.

Only installed base system tools  and `ssh` during guided install.

Additional installation:
- sudo (required by `setup.sh`
  - `su -` and `usermod -aG sudo control` to make the `control` user a sudoer. Must log in / out of `control` user to make changes.
- git (required for `git clone`)

`git clone https://github.com/uwardlaw/vater`
`cd vater/control-services/bin`
`./setup.sh`

Fails with:
```
Err:5 https://download.docker.com/linux/ubuntu bullseye Release
  404  Not Found [IP: 13.226.97.8 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Per this [article](https://rotelok.com/bad-idea-of-the-day-disable-secure-repository-check-apt/) we can use

**Comment by rylagek** [comment]
[Alternative](https://www.howtoforge.com/how-to-install-docker-on-debian-11/) way to install docker on `Debian 11`. `Ubuntu` specific downloads could be the issue since it isn't **just** `Debian`. The steps linked might be longer but can definitely be added to our script

**Comment by uwardlaw** [comment]
There were errors with making a new branch for the issue and then pulling in `setup.sh`, but that's user imposed. 

New error due to `python3` packages:
```
control@control:~/vater/control-services/bin$ vater restart
Traceback (most recent call last):
  File "/home/control/vater/control-services/cli/vater.py", line 2, in <module>
    from config import Config
  File "/home/control/vater/control-services/cli/config.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by uwardlaw** [comment]
Total size is `721M`, packages pushed to branch.

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or interim solution
