### ISSUE TITLE
Implement reading semaphore password from env variable for vater CLI

### ISSUE THREAD

**Issue by rmfirth** [dev4vater/vater#173]
The vater CLI currently expects user input to provide a password to Semaphore when running semaphore tasks. For automated scripts (such as the Jenkins job in #167 ) this is an issue because the script is interrupted by the prompt. Instead, vater should not prompt for a password if a `SEMAPHORE_PASSWORD` environment variable is present, thus allowing the script to continue uninterrupted.

**Comment by uwardlaw** [comment]
This might be more complicated than first look. We avoided placing passwords in plain text anywhere unless the device is configured for `dev` where the defaults can be used. 

Do you mean to pass an environment variable not available from the shell / in memory? Maybe this is better solved with Vault?

**Comment by rmfirth** [comment]
@uwardlaw A script like a Jenkins job can include non-plaintext credentials (even without a Vault implementation) and provide them as environment variables to the CLI, so that is the main use case I am envisioning here, does that make sense?

**Comment by uwardlaw** [comment]
If you've briefly considered security, sounds good. Can discuss more over the PR.

**Comment by marissaeinhorn** [comment]
Not required for RANS connectivity. Foundry will manage this piece
