### ISSUE TITLE
Use static IPs for `control`

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#178]
When `control` was powered on after a datacenter power failure, DHCP provided a different IP address.  To restore normal functionality, environment variables in `semaphore` had to be manually changed

**Comment by rylagek** [comment]
This is a consistent issue for the lab environment as well

**Comment by Donovan-Medina** [comment]
How should this be addressed?
Is packer playing a role in creating the **control** --> create provision?
Or, should this be handled by the setup.sh?

Same question for the warning banner?
