### ISSUE TITLE
Develop ansible script for post deployment action

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#180]
Ansible script must complete the following actions post deployment:

- [x] Promote DC server
- [x] Join workstations to domain
- [x] Use AD module for fake users, machines #184

**Comment by marissaeinhorn** [comment]
Promoting a [DC](https://dteslya.engineer/automation/2019-02-19-configuring_vms_with_ansible/)

**Comment by marissaeinhorn** [comment]
Once this script is run, we will need to take another snapshot and consolidate.  This is inappropriate on the 'DC' server because reverting a snapshot will cause issues within the domain.  

For the workstations, as long as passwords don't expire reverting machine snapshots shouldn't be a problem.  [article](https://petri.com/working-with-domain-member-virtual-machines-and-snapshots)

**Comment by marissaeinhorn** [comment]
Powershell command to promote DCServer 
`Install-ADDSForest -DatabasePath "C:\NTDS" -DomainMode WinThreshold -DomainName "yavin.local" -DomainNetbiosName "yavin" -Force:$true -ForestMode WinThreshold -LogPath "C:\Logs" -SafeModeAdministratorPassword(ConvertTo-SecureString -String 12qwaszx!@QWASZX -Force -AsPlainText) -SysvolPath "C:\SYSVOL"`

**Comment by rylagek** [comment]
We might need to enable winrm as a post deployment action bc when it's enabled during the packer build it shows that it's already enabled bc packer uses winrm for the communicator

**Comment by rylagek** [comment]
[DNS config](https://social.technet.microsoft.com/wiki/contents/articles/52765.windows-server-2019-step-by-step-setup-active-directory-environment-using-powershell.aspx)

**Comment by marissaeinhorn** [comment]
Resources:
[ansible vsphere modules](https://docs.ansible.com/ansible/latest/collections/community/vmware/index.html)
[run shell commands](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_shell_module.html#ansible-collections-community-vmware-vmware-vm-shell-module)
[ex1](https://jcpowermac.github.io/)
[ex2](https://4sysops.com/archives/automate-windows-without-network-connectivity-with-ansible/)

**Comment by marissaeinhorn** [comment]
Playbook error 
```
Listing playbook hosts failed: exit status 4 ERROR! 'community.vmware.vmware_vm_shell' is not a valid attribute for a Play The error appears to be in '/tmp/semaphore/repository_4_12/tasks/promoteDC.yml': line 1, column 3, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: - name: Promote DC server ^ here
```

**Comment by marissaeinhorn** [comment]
Error connecting to vsphere
```
 'Unable to connect to vCenter or ESXi API at 192.168.1.13 on TCP/80: EOF occurred in violation of protocol (_ssl.c:1131)'
```

Attempted using port 80 & 443

**Comment by marissaeinhorn** [comment]
Ansible script only promotes the last domain controller. output

```
1:03:37 PM
TASK [Promote DC] **************************************************************
1:03:37 PM
included: /tmp/semaphore/repository_4_18/tasks/promoteDC.yml for 192.168.100.20 => (item=student01)
1:03:37 PM
included: /tmp/semaphore/repository_4_18/tasks/promoteDC.yml for 192.168.100.20 => (item=student02)
1:03:37 PM
included: /tmp/semaphore/repository_4_18/tasks/promoteDC.yml for 192.168.100.20 => (item=student03)
1:03:37 PM
included: /tmp/semaphore/repository_4_18/tasks/promoteDC.yml for 192.168.100.20 => (item=student04)
1:03:37 PM
1:03:37 PM
TASK [Promote DC server for student01] *****************************************
1:03:40 PM
changed: [192.168.100.20]
1:03:40 PM
1:03:40 PM
TASK [Debug promotion] *********************************************************
1:03:40 PM
ok: [192.168.100.20] =>
1:03:40 PM
shell_command_output:
1:03:40 PM
changed: true
1:03:40 PM
failed: false
1:03:40 PM
msg: 4704
1:03:40 PM
uuid: 423d119c-d515-b916-a2dc-dbfef8a3773f
1:03:41 PM
1:03:41 PM
TASK [Promote DC server for student02] *****************************************
1:03:43 PM
changed: [192.168.100.20]
1:03:43 PM
1:03:43 PM
TASK [Debug promotion] *********************************************************
1:03:43 PM
ok: [192.168.100.20] =>
1:03:43 PM
shell_command_output:
1:03:43 PM
changed: true
1:03:43 PM
failed: false
1:03:43 PM
msg: 4776
1:03:43 PM
uuid: 423d119c-d515-b916-a2dc-dbfef8a3773f
1:03:43 PM
1:03:43 PM
TASK [Promote DC server for student03] *****************************************
1:03:45 PM
changed: [192.168.100.20]
1:03:45 PM
1:03:45 PM
TASK [Debug promotion] *********************************************************
1:03:45 PM
ok: [192.168.100.20] =>
1:03:45 PM
shell_command_output:
1:03:45 PM
changed: true
1:03:45 PM
failed: false
1:03:45 PM
msg: 4860
1:03:45 PM
uuid: 423d119c-d515-b916-a2dc-dbfef8a3773f
1:03:45 PM
1:03:45 PM
TASK [Promote DC server for student04] *****************************************
1:03:48 PM
item: student03
1:03:48 PM
- ansible_loop_var: item
1:03:48 PM
include: promoteDC.yml
1:03:48 PM
include_args: {}
1:03:48 PM
item: student04
1:03:48 PM
changed: [192.168.100.20]
1:03:48 PM
1:03:48 PM
TASK [Debug promotion] *********************************************************
1:03:48 PM
ok: [192.168.100.20] =>
1:03:48 PM
shell_command_output:
1:03:48 PM
changed: true
1:03:48 PM
failed: false
1:03:48 PM
msg: 4972
1:03:48 PM
uuid: 423d119c-d515-b916-a2dc-dbfef8a3773f
1:03:48 PM
1:03:48 PM
TASK [Debug promote DC] ********************************************************
1:03:48 PM
ok: [192.168.100.20] =>
1:03:48 PM
promoteResult:
1:03:48 PM
changed: false
1:03:48 PM
msg: All items completed
1:03:48 PM
results:
1:03:48 PM
- ansible_loop_var: item
1:03:48 PM
include: promoteDC.yml
1:03:48 PM
include_args: {}
1:03:48 PM
item: student01
1:03:48 PM
- ansible_loop_var: item
1:03:48 PM
include: promoteDC.yml
1:03:48 PM
include_args: {}
1:03:48 PM
item: student02
1:03:48 PM
- ansible_loop_var: item
1:03:48 PM
include: promoteDC.yml
1:03:48 PM
include_args: {}

```

**Comment by marissaeinhorn** [comment]
Ansible script executes with error

```
TASK [Promote DC server for student01] *****************************************
11:45:36 AM
fatal: [192.168.100.20]: FAILED! => changed=false
11:45:36 AM
cmd_line: '"c:\windows\system32\windowspowershell\v1.0\powershell.exe" -command "mkdir test"'
11:45:36 AM
end_time: '2022-02-28T17:45:32+00:00'
11:45:36 AM
exit_code: 1
11:45:36 AM
msg: Failed to execute command
11:45:36 AM
name: powershell.exe
11:45:36 AM
owner: Administrator
11:45:36 AM
start_time: '2022-02-28T17:45:31+00:00'
11:45:36 AM
uuid: 423d7984-41ae-5615-19fe-9182e37c2e66

```

**Comment by marissaeinhorn** [comment]
Pivoting to using uuids.  Error: installing package, add to setup.sh
```
3:00:39 PM
TASK [debug] *******************************************************************
3:00:39 PM
fatal: [192.168.100.20]: FAILED! =>
3:00:39 PM
msg: You need to install "jmespath" prior to running json_query filter
```

**Comment by marissaeinhorn** [comment]
End of day Monday notes: @rylagek 
- `promoteDC.yml` will run for `student01`.  Playbook is currently set to run independently of `createRange.yml`.  To change that remove the `host` block and `tasks` and remove the extra indents.
- Ideally `promoteDC.yml` will run from `createRange.yml` and run for each iteration of student01, student02 ect. Inside `promoteDC.yml` there are several with_item loops that use the iterator {{item}}.  Running `promoteDC.yml` from `CreateRange.yml` which also uses with_sequence loops using the iterator {{item}} is proving difficult.  
- Didn't have time to debug the new loop function in ansible [documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html).  I think the new loop structure will work but I ran out of time.  Commented out code at the bottom of `CreateRange.yml` shows the current progress.  When uncommented playbook will fail without any errors.

**Comment by marissaeinhorn** [comment]
DCserver promotes for all students!

**Comment by marissaeinhorn** [comment]
`addusers.ps1` script doesnt run properly.  Converting commands to use `New-ADUser` [reference](https://adamtheautomator.com/new-aduser/)

**Comment by marissaeinhorn** [comment]
@rylagek 
Need to update windows2019 template with new `load_fakedomainusers2.ps1` script.  Located in uwardlaw/rous/bin

**Comment by rylagek** [comment]
https://www.windowscentral.com/how-create-unattended-media-do-automated-installation-windows-10

To generate updated autounattend.xml files follow the steps in this guide

Unattended windows install files are extremely specific and will completely break the packer build process before it can even start.

**Comment by marissaeinhorn** [comment]
Added script to join domain `joinDomain.ps1`.  Its located in iss180 `~/rous/vms/dco/scripts`  the task template will run the script and delete it so that credentials are not left on the device.  @rylagek please add it to all the windows 10 templates in `C:\Windows\Temp`

**Comment by rylagek** [comment]
Script worked!
