### ISSUE TITLE
Define RAM and storage requirements for DCO range 

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#182]
Needed for CCB/COTR support to deploy `VATER` and 11 student ranges on labnet

**Comment by rylagek** [comment]
VM | Ram | Storage
---|---|---
build-windows2019 | 4Gb | 50Gb
win_10_dco | 8Gb | 80Gb
win_10_wkst1 | 8Gb | 50Gb
win_10_wkst2 | 8Gb | 50Gb
win_10_wkst3 | 8Gb | 50Gb
win_10_admin | 8Gb | 50Gb
effects_kali | 4Gb | 20Gb
onion_sensor | ? | ?
onion_dco | ? | 99Gb
TOTAL | 48+ Gb | 350+ Gb
11 Stu ranges | 528 Gb Ram | 3850 Gb Storage

Goal is to decrease the `win_10_wkst` resources as much as possible to provide extra resources for `security onion`
We should also use `terraform` to scale down ram allocations after the `packer` builds

**Comment by rylagek** [comment]
Also need to add `VATER` control resource requirements

**Comment by rylagek** [comment]
and the `inet-rtr` requirements

**Comment by rylagek** [comment]
Attempting to reduce `windows 10` boxes to 4Gb Ram and 40Gb Storage
Minimized `inet_rtr` to 1Gb ram and 2Gb storage

**Comment by rylagek** [comment]
Those minimums worked - going to test reducing the windows boxes by another 10Gb
