### ISSUE TITLE
Find alternative to hard coded vcenter creds in terraform file

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#20]
- [ ] Edit `restart.sh` to prompt for vSphere credentials
- [ ] Add `vSphereEnvironment.tf` to `rous`
- [ ] Add `vater/control-services/data/Semaphore/vSphere.auto.tfvars`

Pulled out of research in #74

**Comment by marissaeinhorn** [comment]
https://registry.terraform.io/providers/hashicorp/vault/latest/docs
https://www.vaultproject.io/docs/what-is-vault

**Comment by marissaeinhorn** [comment]
Not required for RANS connectivity. Foundry will manage this piece
