### ISSUE TITLE
Modify VM naming conventions in terraform

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#206]
Currently VMs are located in folders `class/student` and have a non-unique name.  This makes backend management for the contractors more difficult. Modify terraform to name vms `class#_student#_name` 

This will likely simplify the process for ansible performing post deployment actions since ansible is currently looking up uuids for vms.  If the name is a unique id then we can eliminate 2 complicated tasks.

**Comment by marissaeinhorn** [comment]
Completed in uwardlaw/rous/iss180

**Comment by rylagek** [comment]
@marissaeinhorn propose changing order to name_class#_student# to make the default view in vcenter meaningful - as it is we only see class# listed when you open a folder
