### ISSUE TITLE
Create terraform modules for each enclave

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#209]
Determine whether using terraform modules or changing the folder structure is the better choice moving forward. Terraform can act on a single item using the `-target` command but this will be tedious for enclaves.  Refractor the code into [modules](https://www.terraform.io/language/modules/develop) so that selective builds and destroys are possible.  

- [ ] Required Modules Updated after RANS meetings & UCWT course content review
- Ops Enclave (OCO/DCO)
- OCO practice
- Windows
- Linux
- Python
- Class Resources
- High Tide
- Falling Star
- Mini Concord Dawn
- Dr Boom

- [ ] Make sure vm names for each terraform resource match vm name in vsphere
- [ ] Test with create range/destroy range tasks
- [ ] Test with restart/revert/rebuild VM tasks

**Comment by jodilynn98** [comment]
DCO module is complete. Some things to note when making the other modules:

- Place the module declaration in the main.tf file in the root terraform directory using the following convention:
    ```
     module "<name of module>" {
         source = "./modules/<name of module directory>"
         # list all variables associated with the module in the following format
         <name of variable> = var.<name of variable>
    }
- Add all variables declarations to the variables.tf file in the root directory
- Add all variable definitions to the vsphere.auto.tfvars file in the root directory
- Create a new module directory in terraform/modules. This directory needs to correspond to the name used in the module declaration.
- Create a variables.tf file that matches the variables.tf file in the terraform root directory
- Place all other .tf files in this module directory. The name of your module code .tf file needs to match the name of the module in the module declaration.

*You do not necessarily need a variables.tf in terraform/modules/<module directory> if all your variables are declared in the individual .tf files. However, you have to add all variables to the variables.tf in the terraform root directory.*

In order to test the module you can run the following commands from the terraform root directory"
` terraform init `
`terraform plan -target="module.<name of module>"`
`terraform plan -target="module.<name of module>" -var-file="vsphere.aut.tfvars"`
*If you do not specify the -var-file while running `terraform plan`, you will have to manually input all variables*

```
terraform
   ├── main.tf
   ├── variables.tf
   ├── vsphere.auto.tfvars
   └── modules
   │   └── dco
   │       ├── dcotest.tf
   │       ├── student.tf
   │       ├── variables.tf
   │       └── vsphere.tf
