### ISSUE TITLE
Diagrams as Code and Code as Diagrams with PlantUML

### ISSUE THREAD

**Issue by rylagek** [dev4vater/vater#214]
In order to promote clean code and visually inspect for dependencies or design issues we can use [PlantUML](https://plantuml.com/).
There are several [guides](https://crashedmind.github.io/PlantUMLHitchhikersGuide/#) available and we can use [this site](https://www.hcl2json.com/) to easily convert from `hcl`, `yml`, and `json` in order to diagram almost all code (even content) easily.

- [ ] Diagram VATER
- [ ] Diagram ROUS
- [ ] Diagram generic content
- [ ] Identify design dependencies
- [ ] Look into automating the PlanUML diagram generation process
- [ ] Need to identify all of the file types we use

**Comment by rylagek** [comment]
HCL to json conversion [here](https://www.hcl2json.com/) converts pkrvar files to json ok, but `vsphere.pkr.hcl` uses variables that must be enveloped in `" "`
Should be able to write a script to convert files directly to diagram images for easy documentation using `sed` and locally hosted conversion tools for `hcl` to `json` and then locally hosted `PlantUML`

**Comment by rylagek** [comment]
HCL for the .tf needs the variables in the `depends_on` list put into quotes for json conversion

**Comment by rylagek** [comment]
If yml is not recognized - convert to json

**Comment by rylagek** [comment]
Draw.io works with PlantUML - saving as PNG is an unnecessary step

**Comment by rylagek** [comment]
The built in PlantUML processing gives an error for JSON processing - next best option is to save as SVG and import to draw.io

**Comment by marissaeinhorn** [comment]
Diagrams saved in 17S-OCO/VATER folder.  Need to save 1 complete svg for the pilot version and save component files in dev4vaters google drive folder.
