### ISSUE TITLE
`Setup.sh` fails at go install

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#240]
At line 31-35 in `setup.sh` the script fails to continue executing after installing go.  Need to debug and fix script to allow for full install of control

**Comment by marissaeinhorn** [comment]
This bug was found during the RANS demo attempting to install VATER on ubuntu desktop.  Im not seeing this problem repeated when installing control on ubuntu server on virtualbox.  @Donovan-Medina @Timo604 please document any setup problems here when you create your development environment

**Comment by marissaeinhorn** [comment]
Testing will also close #149

**Comment by Donovan-Medina** [comment]
Upon testing, go installs fine from the setup.sh. Checking into the Rous portion. But I think #240 as far as _go_ working is good.

**Comment by Donovan-Medina** [comment]
setup.sh fails after line 184 
`Change origin urs for $SETUP_REPO and $CONFIG_REPO`
It cannot appropriately pull from "git@vater:uwardlaw/vater.git" nor "git@rous:uwardlaw/rous.git"
The *ORG_OR_USER* is hardcoded as a specific user, in this case "uwardlaw"

**Comment by Donovan-Medina** [comment]
I know that vater is now currently under dev4vater, will rous be moved under dev4vater or a 333rd controlled user?
