### ISSUE TITLE
Modular packer windows active directory templates 

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#248]
Building packer templates with swapable variables and multiple small GPOs will allow us to reuse code across the 4 planned AD environments.  Pieces that should be modular

DC servers:
- ip address
- hostname
- domain name
- dns server 
- child domains 
- netbios name
- credentials
- share drives
- user accounts
 
GPOs:
- firewall rules - we can break these out by rule so we can mix and match them when we go to build windows & OCO/DCO enclaves
- user groups - make multiple groups (enterprise admins, developers, executives ect.) so adding users with specific permissions is easier

Workstations: 
- ip address
- hostname
- domain to join

**Comment by rylagek** [comment]
The below notes will be processed as we build out the windows dev SOPs and then added to the wiki for dev continuity

### Notes from talking to Gabe:
Disable changing password and set expiration to max `999`
GPMC - group policy management console
Need RSAT on Admin
FOD - feature on demand 2004 is required above 1909 - for every new version need to check compatibility
Lockout 3
GPME - group policy management environment
Can set specific desktop background by overwriting each boot
check remat
`dcdiag` - no fails, need all passes
`repadmin` - show replications
script OV build to run on a restart
GUI -> details -> UID
Power needs to be set to no sleep via GPO
Process Registry settings regardless of GPO change (only if airgapped)
use profile copy and change SID to create mult user profiles
Tablechart works too - can process CSVs
ORCA - install windows ADK and SDK - get EVERYTHING
- download and make for another box
- MSI can be automated as an MST (answer key and MSI)
- can also access MSI exec and installer switches to make silent install

example of registry key possiblities: EULA accept is just a reg key

Copy files w/ GPO takes milliseconds vs the hours Packer can take
GPME -> Files -> Computer/User Config
