### ISSUE TITLE
Create Windows dev dedicated VM

### ISSUE THREAD

**Issue by rylagek** [dev4vater/vater#251]
Blocking #248  
Need a dedicated VM with the following:

- [x] install a "good" web browser
- [x] install windows SDK
- [x] install windows ADK
- [x] verify/install ORCA.exe

windows 10 and servers 2016/2019 are all supported - might be best to install on top of the vms we have for `WSIM` but a fresh install would probably be less hassle as windows system image manager already required parts of the above installation requirement i.e. wouldn't be a clean install

**Comment by Timo604** [comment]
VM is created and is called Windows Dev. it's in vSphere under DUCKnet DEVELOPMENT> Fundamentals Dev
