### ISSUE TITLE
Redstar arch hosts

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#269]
Webserver
- [x] IP `10.62.29.99`
- [x] Web server configuration files [redstarWeb.zip](https://github.com/dev4vater/vater/files/8911026/redstarWeb.zip)
- [x] Upgrade arch keyring.  Pacman command named `archlinux-keyring`
- [ ] Install postfix - afrl used pacman
- [ ] Copy master.cf from files to `/etc/postfix/master.cf`
- [ ] Copy main.cf from files to `/etc/postfix/main.cf`
- [ ] Copy aliases from files to `/etc/postfix/aliases`
- [ ] Run postfix `newaliases` command to update database
- [ ] Restart postfix 
- [ ] Install dovecot - afrl used pacman
- [ ] Copy dovecot.conf from files to `/etc/dovecot/dovecot.conf`
- [ ] Copy dovecot conf.d directory to `/etc/dovecot`
- [ ] restart dovecot
- [ ] add user accounts

Mailserver
- [x] IP `10.62.29.63`
- [x] Files 
[redstarMail.zip](https://github.com/dev4vater/vater/files/8911064/redstarMail.zip)
- [x] Users in discord thread
- [x] Same steps as webserver - need to verify with grant if this is correct

VPN server
- [x] IP `10.62.29.99`
- [ ] files 
 [redstarVPN.zip](https://github.com/dev4vater/vater/files/8911048/redstarVPN.zip)

**Comment by JohnLieman** [comment]
Webserver - Had to install php-apache, (potentially) missing the dovecot/postfix files. They may be the same ones in the redstarMail.zip but not sure.

**Comment by JohnLieman** [comment]
Mail server - dovecot doesn't automatically create /etc/dovecot, created the directory manually. If it doesn't work properly later on this is a probable cause. Modified provided postfix main.cf and aliases files to remove ansible variables, hardcoded the domain and users in. Seems to be working now. 
VPN server - provided pki.sh script doesn't handle input prompts so it doesn't complete without manual input. Easy-rsa does have methods to automate some of the inputs but it seems a bit complicated. Will have to come back to this later.

**Comment by JohnLieman** [comment]
Corrections based on AFRL code:
Dovecot + Postfix only need to be configured on the mail server, using provided configuration files.
Users only need to be added to the mail server.

**Comment by JohnLieman** [comment]
VPN Server:
Modified `pki.sh` to remove user input prompts. Set `EASYRSA_BATCH '1'` and added `nopass` flag to `easyrsa build-ca` because the script kept pausing to request CA passphrase input.

There are ways to automate passing the passphrase, but I couldn't get them to work. If security is a concern I can invest more time in figuring it out, but for now the nopass flag lets the script run to the end w/o input.
