### ISSUE TITLE
Install Nginx on control as part of setup

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#276]
On labnet nginx allows for a link on the instructor splash page to access VATER.  Install nginx and configure according to this [article](https://computingforgeeks.com/how-to-configure-nginx-proxy-for-semaphore-ansible-web-ui/).  Note that semaphore runs on port 4000 for VATER.  Verify labnet configurations with @rylagek and notes [page](https://docs.google.com/document/d/19eRq2lTz1YI8L10dZniZTCzYjJNlvnm6/edit)

Add steps to setup.sh and describe changes required to transition from ducknet to labnet in the wiki page.

**Comment by JohnLieman** [comment]
Added nginx installation to `setup.sh`. I also moved a copy of `semaphore.conf` used by the current labnet controller into the `rous/vms/control` directory with the certs. Updated `locations.txt` with the command to move it to the appropriate location. 

Currently the controller on DUCKNet only supports http. I can't generate an SSL cert for a private IP, so I can't enable https without some shenanigans.
