### ISSUE TITLE
Add a task template to Create Class to rebuild machine by name

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#28]
- [x] Blocked by #95 
- [ ] Add `rebuildVM.yml` to `rous/ansible`
- [x] Add `Rebuild VM` task template to `setupNewClass.py`

**Comment by marissaeinhorn** [comment]
Need playbook to run `terraform apply -auto-approve -target="<resource name >"`  with all of the command line provided additional variables. The resource name listed in the terraform file should be identical to the VM name listed in `group_vars`

**Comment by marissaeinhorn** [comment]
Will need to rerun any ansible post deployment scripts on the rebuilt machine.  Need to add a variable to `group_vars` to list applicable scripts

**Comment by marissaeinhorn** [comment]
Need to add in functionality to specify an entire enclave instead of requiring instructor to select each individual VM

**Comment by marissaeinhorn** [comment]
- [ ] Update task template to contain variables for `vmName`, `enclave`, and `studentNumber`.  `vmName` must be the same as terraform resource name

**Comment by marissaeinhorn** [comment]
Working and tested in branch iss180
