### ISSUE TITLE
Add a task template to Create Class to run training mission

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#30]
The purpose of this feature is to add missions run by `task templates` under the `class#####` project. We could take a couple of approaches for this.

1. Create a `ansible/missions/[name]` with relevant scripts and two playbooks `start.yml` and `stop.yml`. Create two task templates for each mission that's in the folder, `Start [name]` and `Pause [name]`.

**Comment by uwardlaw** [comment]
This is not a necessary component for milestone `v0.1` and should be reconsidered for `v0.2`.

**Comment by marissaeinhorn** [comment]
Run training mission will be different for each class.  DCO TM actions in #200
