### ISSUE TITLE
Develop instructor guide

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#44]
Guide should include a description of how to:
- [ ] Make teams
- [ ] Assign teams to projects
- [ ] Assign and remove people from teams

**Comment by uwardlaw** [comment]
Guide should include a description of how to make:
- [ ] Make teams
- [ ] Assign teams to projects
- [ ] Assign and remove people from teams

**Comment by marissaeinhorn** [comment]
Will be included in wiki
