### ISSUE TITLE
Range change management board with PnP, COR, and COTR

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#64]
- There are 20 unused OCO ranges we can remove to reap resources
~~- Size analysis for the size of `Fundamentals` enclave~~
- Communication with `COTR`
- MDT range might have some resources that can be cut, it's built to support 2 class of 16, but MDT only runs 1 in 17X at a time
- CWO Captstone range only ever uses 1 at time Raulston schedules, Capt Conrad for UCWT

**Comment by uwardlaw** [comment]
Change board request sent

**Comment by uwardlaw** [comment]
@Mercerudy is helping out while @comeste10 is gone.

@rylagek We need the size estimates

**Comment by comeste10** [comment]
Confirmed with Mr. Mooney, Lt Martinez, and TSgt Boltz, curriculum change board is not required, we're good to proceed with the range side of the change management board, have the confirmation of this status confirmed in email

**Comment by comeste10** [comment]
> @uwardlaw  @rylagek We need the size estimates

any progress made on this? also what was the scope of the sizes estimates being requested?

**Comment by uwardlaw** [comment]
This is dependent on the final packer builds of the CWO OCO/DCO enclave, so
no update

**Comment by uwardlaw** [comment]
I was able to install `Control` on `vSphere Client version 7.0.3.00300` and `VMware ESXi, 7.0.3, 19035710`.

I gave `control`:
- 1 GB RAM
- 40 GB disk
- 1 vcpu

<img width="1149" alt="control-vshere" src="https://user-images.githubusercontent.com/55300322/146654058-58892636-ca13-4d30-8b24-a8cc12a3775d.PNG">

Only 10.2 GB of disk were used after a `./setup.sh` and `vater restart`.

![image](https://user-images.githubusercontent.com/55300322/146654053-c4cc1e4d-3233-48b0-a161-96678df6ff03.png)

**Comment by marissaeinhorn** [comment]
VATER pilot review meeting successful and approved to move forward with transferring falling star and high tide to labnet
