### ISSUE TITLE
Terraform deploy `Fundamentals` enclave

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#67]
- [x] new vms from iso (DC, 2019, 10 domain, 10 workgroup) with basic configs for testing
- [x] WINDOWS_10_DOMAIN_TEMPLATE
- [ ] WINDOWS_10_WORKGROUP_TEMPLATE
- [ ] WINDOWS_2019_TEMPLATE
- [ ] WINDOWS_2019_DC_TEMPLATE

(Removed tasks after deciding that Terraform will not customize)
~~Write terraform file to clone VMS and join them to domain~~
~~Test terraform clones to ensure networking connectivity/configs is preserved~~
~~Document command line configs for input into packer templates~~

**Comment by marissaeinhorn** [comment]
[x] new vms from iso (DC, 2019, 10 domain, 10 workgroup) with basic configs for testing

**Comment by marissaeinhorn** [comment]
- [ ] Write terraform file to clone VMS and join them 
- [ ] Test terraform clones to ensure networking connectivity/configs is preserved 
- [ ] Document command line configs for input into packer templates

**Comment by uwardlaw** [comment]
Maybe [this](https://github.com/hashicorp/terraform-provider-vsphere/issues/231#issuecomment-344300342) is useful. You can turn off terraform waiting for IPs with `wait_for_guest_net = false`

**Comment by marissaeinhorn** [comment]
Solved no operating system found errors when deploying windows 10 VM- firmware must be set to efi if template uses efi.  bios is the default. article[](https://github.com/hashicorp/terraform-provider-vsphere/issues/441)

**Comment by marissaeinhorn** [comment]
Logs from VM customization are stored on the VM in C:/Windows/TEMP/vmware-imc/guestcust.log

**Comment by marissaeinhorn** [comment]
Check if winrm is disabled on win 10 template

**Comment by marissaeinhorn** [comment]
Configured winrm on windows 10 template, install still failing during customization but the clone is further along in the install process.

Next step is to add connection block to terraform file explicitly specifying how to connect to winrm [article](https://ripon-banik.medium.com/using-winrm-in-terraform-82168362c2ed)

**Comment by uwardlaw** [comment]
We suspect that WinRM is not configured properly and causing the `customization` block to fail. `Event Viewer` says:

```
The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests.
```

and

```
WSMan operation Enumeration failed, error code 2150858770
```

We suspect this might be due to misconfiguration of `WinRM`. Windows [documentation](https://docs.microsoft.com/en-us/windows/win32/winrm/installation-and-configuration-for-windows-remote-management) says:

```
- By default, no WinRM listener is configured. Even if the WinRM service is running, WS-Management protocol messages that request data can't be received or sent.
- Internet Connection Firewall (ICF) blocks access to ports.
```

**Comment by marissaeinhorn** [comment]
Changed winrm service account to run as `Local Service`

**Comment by marissaeinhorn** [comment]
Added `auto_logon` and `auto_logon_count` to main.tf file.  Allows terraform to finish customization without errors.

**Comment by marissaeinhorn** [comment]
Adding other windows machines to Terraform file.  Template clones but OS is not installed, removed iso from template image to fix the error

**Comment by marissaeinhorn** [comment]
Writing terraform file to clone DC server, debugging error:
╷
│ Error: error sending customization spec: A specified parameter was not correct: spec.identity.userData.computerName
│
│   with vsphere_virtual_machine.cloned_virtual_machine1,
│   on main.tf line 86, in resource "vsphere_virtual_machine" "cloned_virtual_machine1":
│   86: resource "vsphere_virtual_machine" "cloned_virtual_machine1" {
│

**Comment by marissaeinhorn** [comment]
Error during deployment of DC template `windows setup could not configure windows to run on this computer's hardware`

**Comment by marissaeinhorn** [comment]
[Article on AD provisioner with description on winrm requirements](https://xkln.net/blog/getting-started-with-terraform-and-the-active-directory-provider/)

**Comment by marissaeinhorn** [comment]
To promote domain controller added `remote-exec` [block] (https://www.terraform.io/docs/language/resources/provisioners/remote-exec.html) and `connection` [block](https://www.terraform.io/docs/language/resources/provisioners/connection.html) specifying winrm settings

**Comment by marissaeinhorn** [comment]
Winrm executing but connection fails with error 
```
null_resource.dcpromo_command (remote-exec): Connecting to remote host via WinRM...
null_resource.dcpromo_command (remote-exec):   Host: 10.0.0.26
null_resource.dcpromo_command (remote-exec):   Port: 5985
null_resource.dcpromo_command (remote-exec):   User: Administrator
null_resource.dcpromo_command (remote-exec):   Password: true
null_resource.dcpromo_command (remote-exec):   HTTPS: false
null_resource.dcpromo_command (remote-exec):   Insecure: false
null_resource.dcpromo_command (remote-exec):   NTLM: false
null_resource.dcpromo_command (remote-exec):   CACert: false
```
added null_resource to address potential race condition [terraform issue](https://github.com/hashicorp/terraform/issues/17728)

**Comment by marissaeinhorn** [comment]
terraform `local-exec` executes commands on the machine running terraform not the resource [article](https://ilhicas.com/2019/08/17/Terraform-local-exec-run-always.html)

**Comment by marissaeinhorn** [comment]
Moved `connection` block into `remote-exec` block.  Terraform no longer attempts to connect before VM is done creating.  Connection still fails

```
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec): Connecting to remote host via WinRM...
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec):   Host: 10.0.0.26
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec):   Port: 5985
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec):   User: Administrator
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec):   Password: true
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec):   HTTPS: false
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec):   Insecure: true
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec):   NTLM: false
vsphere_virtual_machine.cloned_virtual_machine1 (remote-exec):   CACert: false
```

**Comment by marissaeinhorn** [comment]
From windows command line `winrm get winrm/config` gets current winrm settings.

terraform `run_once_command_list` executed `winrm quickconfig -force` but not subsequent commands

**Comment by marissaeinhorn** [comment]
`winrm` functioning on DC.  Previous errors due to routing problem from control to VM.   Moved VM onto control's network adapter and successfully ran test command.

Next incorporate dcpromo command

**Comment by marissaeinhorn** [comment]
Added `/unattend` to the dcpromo command, previous install hung after command was issued by `remote-exec`

**Comment by marissaeinhorn** [comment]
Successfully promoted domain controller, but when system reboots terraform exits with an error.  Added a delayed reboot and winrm disconnect to prevent the [problem](https://github.com/hashicorp/terraform/issues/17844)

**Comment by marissaeinhorn** [comment]
In `provisioner` block added `on_failure="continue"` will ignore errors generated by this block.  [reference](https://anthonyspiteri.net/quick-fix-terraform-linux-remote-exec-provisioner-errors-without-exit-status/)

**Comment by uwardlaw** [comment]
Terraform cannot configure multiple `Windows 2019 DCs` because the IP addresses are all the same. We need a way to distinctly route between different student VMs.

The first step is removing hardcoded IP addresses from the Terraform file so they can be set by Ansible.

Then we need to add the `student##-core` routers. The connections between the `student##-core` router and `control` need to be unique while the connections behind `student##-core` router can be static set. We will reach things behind the `student##-core` with SSH bastion.

Blocked by #71 and #26

**Comment by marissaeinhorn** [comment]
Attempting to join windows 10 machine to the domain.  `terraform apply` exits with the following error

```
 Error: error sending customization spec: Cannot complete customization.
│
│   with vsphere_virtual_machine.cloned_virtual_machine2,
│   on main.tf line 227, in resource "vsphere_virtual_machine" "cloned_virtual_machine2":
│  227: resource "vsphere_virtual_machine" "cloned_virtual_machine2" {
│
╵

```

**Comment by marissaeinhorn** [comment]
Adding `core router` to tf file.  Vyos hostnames must not include special characters.  [reference](https://github.com/ansible/ansible/issues/24225)

**Comment by marissaeinhorn** [comment]
vyos requires a dhcp server to be running on the network so a `remote-exec` provisioner can connect over ssh.

**Comment by marissaeinhorn** [comment]
Addded `file` provisioner block to copy vyos config from `control` to the `core-rtr`.  Config contains static ip address for internal interface

**Comment by marissaeinhorn** [comment]
`remote-exec` shell `$PATH= /usr/local/bin:/usr/bin:/bin:/usr/games`

**Comment by uwardlaw** [comment]
Decision was made to stop using `Terraform` for customization.

**Comment by uwardlaw** [comment]
@marissaeinhorn As the fundamentals enclave is no longer a priority, the milestone marker is being removed and the issue is left over. Please convert any residual problems that affect `VATER` core into new issues for consideration in milestone `v0.2`.

**Comment by marissaeinhorn** [comment]
Closing outstanding issues defined in #289 and #290
