### ISSUE TITLE
Reduce resources used by potentially redundant `vSwitch`

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#73]
Research if port groups need dedicated `vSwitch` or if they can share the same `vSwitch`.

Documentation suggests each port group requires a new `vSwitch` (RFI - docs for `Terraform`

vSwitches a lot of space (RFI - space taken)

**Comment by marissaeinhorn** [comment]
Labnet allows for distributed port groups which will all share the same vswitch
