### ISSUE TITLE
Convert `setupNewClass.py` into Ansible playbook `tasks`

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#75]
This is pulled from #10 

The decision was made to complete the product without using the `tasks` and instead reuse the code in `setupSemaphore.py` in a script `setupNewClass.py`. A task in `createNewClassInSemaphore.yml` calls `setupNewClass.py`.

The right way to do this would be to use a fully Ansible solution. 

There's an open issue right now asking for help https://github.com/ansible-semaphore/semaphore/issues/785

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or intermediate solution
