### ISSUE TITLE
Create enclave `Inventory` from `.tfstate` files

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#77]
- [ ] Add `enclave.inv.j2`
- [ ] Add playbook task to read `.tfstate` files to create enclave `inventory` files

Pulled out of research in #74

**Comment by marissaeinhorn** [comment]
For RANS transition we will not be maintaining data in jinja files.  Terraform automatically creates and maintains the inventory, but we will need to determine if modules introduce any problems with our existing code.
