### ISSUE TITLE
Build technical wiki documentation

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#78]
- [ ] Build out the Wiki with sections for students with available information
   - Access methods to get into infrastructure
   - ROEs (non targetable items)
- [ ] Build out the Wiki with sections for developers with available information
   - Explanations of different technologies at play
   - Technical diagrams and design (draw.io in `vater/diagram`)
   - Relationships between components and design
   - Requirements for different components (`Control` specs)
   - Development workflow
   - How to use different dev tools (e.g. `bin/restart.sh` and `bin/accessContainer.sh`)
- [ ] Build out the Wiki with sections for instructors with available information
  - Buttonology
  - Basic troubleshooting
- [ ] Build out the Wiki with sections for stakeholders with available information
  - Objectives of the project (IaC, benefits)
  - High level explanation of what it does

**Comment by marissaeinhorn** [comment]
https://mad-ducks-vater.readthedocs.io/en/latest/
