### ISSUE TITLE
Initial code review

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#80]
- [ ] Ensure all code is documented and explanations are full
- [ ] Identify obvious deficiencies 
- [ ] Update `README`s with directory level documentation and explanations of different repo components and how to use the different pieces
- [ ] If available, run things through a lint
- [x] Rename variables in `rous/terraform/main.tf`

**Comment by comeste10** [comment]
Made several changes to top-level project Wiki, including addition of a description for Packer

**Comment by marissaeinhorn** [comment]
Documentation will be build into wiki #78

**Comment by marissaeinhorn** [comment]
Python linter [black](https://black.readthedocs.io/en/stable/) from #237
