### ISSUE TITLE
Improve and check `.gitignore` in `rous`

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#86]
There's a preliminary file currently in `rous/.gitignore`. A helpful [question](https://stackoverflow.com/questions/343646/ignoring-directories-in-git-repositories-on-windows). We need to move to service specific `.gitignore` files in their respective directories.

- [ ] Add a `rous/ansible/.gitignore`
- [ ] Add a `rous/terraform/.gitignore`
- [ ] Add a `rous/packer/.gitignore`
- [ ] Alter `rous/.gitignore` to remove service specific items
- [ ] Remove unstaged changes with `git rm --cached [dir/filename]`
- [ ] Check with `git check-ignore *`

**Comment by marissaeinhorn** [comment]
@rylagek We need to verify that `.gitignore` has best practices for `ansible`, `packer` & `terraform`.  Verify all `.gitignore` rules across the code base.

@uwardlaw do you have any updates from Sam on this issue?

**Comment by uwardlaw** [comment]
No. I'd also add that maybe the initial strategy here wasn't great. Multiple files are harder to ignore. Maybe one file in the root directory and then comments / organizing it by services would be better.
