### ISSUE TITLE
Terraform cannot create `class` resources

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#90]
By design terraform either creates or references resources in vsphere.  Any resources shared by a whole class like folders, wikis, code repos will need to be created in a separate workspace for the class to ensure terraform only attempts to create them once

**Comment by uwardlaw** [comment]
Current implementation of the terraform `workspaces` use `class{{ classNumber }}_{{ item }}` which for `classNumber=21012` and `student01` produces `class21012_student01`. Items that are shared by the class should belong to the the `class{{ classNumber }}` workspace.

**Comment by rylagek** [comment]
Need to update this implementation for `CWO/UCWT` specific classes and in doing so, shared resources

**Comment by marissaeinhorn** [comment]
Ansible is building vsphere class folders.  Moving to core enclave to build class wikis ect.

**Comment by uwardlaw** [comment]
I'd think about that, the core enclave is primarily just the core router. It doesn't have any services attached to it. It may be good to create a whiteCellEnclave or something and implement firewall rules / protections at the router connected to the core.

**Comment by marissaeinhorn** [comment]
This will probably be fixed by implementing terraform modules for each enclave
