### ISSUE TITLE
Packer Windows Dependency on Files in Datastore

### ISSUE THREAD

**Issue by rylagek** [dev4vater/vater#97]
Currently dependent on `Windows ISO` and `VMware Tools EXE`

Tasks:

- [ ] get download link for ISO
- [ ] update `os_iso_path` in `win10.auto.pkrvars.hcl`
- [ ] get download link for EXE
- [ ] update `vmtools_iso_path` in  `win10.auto.pkrvars.hcl`

This will create a new issue for security in verifying the hashes of the downloads

**Comment by uwardlaw** [comment]
We can not deploy `vater` on LABNet without internet dependencies removed. Otherwise, we need a very specific manual staging process. Moving to requirement

**Comment by marissaeinhorn** [comment]
`.iso` files must be downloaded and placed in a folder for `packer` to reference.  Windows `.iso` file links only last 24 hours, so even with internet access this will remain a problem

**Comment by uwardlaw** [comment]
Why do we need to automate subsequent iso downloads?

We just take snapshots and reuse the VMs created

**Comment by marissaeinhorn** [comment]
Original goal was to pull the newest download but this will not work with the way windows auto unattended setup runs. Priorities also have shifted away from maintaining the most recent version of OS
